# Generated by Django 5.1.4 on 2025-01-13 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='saved_amount',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='deadline',
            new_name='target_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(default='Untitled Goal', max_length=255),
        ),
    ]
