# Generated by Django 5.1.4 on 2025-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_rename_saved_amount_goal_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='allocation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
