# Generated by Django 5.1.4 on 2025-03-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_allocation_goal_current_balance_goal_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='remaining',
            new_name='remaining_balance',
        ),
    ]
