# Generated by Django 5.1.4 on 2025-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_rename_remaining_goal_remaining_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='allocation',
            new_name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='remaining_balance',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
