# Generated by Django 5.0.7 on 2025-02-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_expense_user_goal_user_income_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
