# Generated by Django 5.0.7 on 2025-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='Untitled Income', max_length=255),
        ),
    ]
