# Generated by Django 5.0.7 on 2025-04-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_income_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
    ]
