# Generated by Django 5.0.7 on 2025-04-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_income_category_alter_income_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
