# Generated by Django 5.0.7 on 2025-04-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_description_remove_income_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='item',
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
