# Generated by Django 5.1.4 on 2025-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_category_remove_income_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
