# Generated by Django 5.0.7 on 2025-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_remove_income_category_remove_income_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
