# Generated by Django 5.1.4 on 2025-03-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_income_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
