# Generated by Django 5.1.4 on 2025-03-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_remove_income_description_remove_income_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
